apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cert-manager-rotate-policy-webhook
  namespace: cert-manager
  labels:
    component: mutating-controller
  annotations:
    cert-manager.io/inject-ca-from: kube-system/rotate-policy-webhook-tls
webhooks:
  - name: rotate-policy-webhook.cluster.local
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: rotate-policy-webhook
        namespace: cert-manager
        path: /mutate/certificates
     rules:
      - apiGroups: ["cert-manager.io"]
        resources:
          - "certificates"
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE